server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: pa55word
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#logging:
#  level:
#    # This will show the whole request filter (middleware) chain it will make it easier to debug
#    # don't use on production
#    org.springframework.security = TRACE